name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build main
      run: cargo build --bin main --verbose
    - name: Build terminal
      run: cargo build --bin terminal --verbose
    - name: Build rest
      run: cargo build --bin api_rest --verbose
    - name: Run tests
      run: cargo test --verbose
